exports.data = {
  "aff": {
    "Altar Community": ,
    "AoD: 7-10 Man": ,
    "AoD247": ,
    "BA Teams": ,
    "Boss Guides/Marathons": ,
    "Boss School": ,
    "Castle Wars United": ,
    "Clue Chasers": ,
    "Deep Sea Fishing": ,
    "Elite Dungeon Teams": ,
    "Fashionscapers": ,
    "Fast Sc ": ,
    "Keyers FC": ,
    "LSKK247": ,
    "Minigames ": ,
    "Nexperts": ,
    "PvMing FC": ,
    "Raids School": ,
    "RS Pocketbook": ,
    "RuneHub": ,
    "RuneScape Forumers": ,
    "RuneScape Friend Channel": ,
    "Skilling": ,
    "Slayer Dungs": ,
    "Solak Community": ,
    "Solak FC": ,
    "Solak247": ,
    "TH Trading": ,
    "The Dueling Club of Gielinor": ,
    "The Liberation": ,
    "Umami FC": ,
    "Vis Wax FC": ,
    "Vorago Discord": ,
    "Player Owned Farms": ,
    "A Cuddle Of Red Pandas": ,
    "LSPVM247": ,
    "Wandoodle & Rago PvM": 
  },
  "soc": {
    "Alright": ,
    "RS Academia": 
  }
};