exports.data = {
	"help": {
			"title": "Comprehensive list of all valid commands",
			"author": {
				"name": "Cape Info",
				"icon_url": "https://i.imgur.com/6c6q2iC.png"
			},
			"description": "{{output}}",
			"footer": {
				"icon_url": "https://cdn.discordapp.com/attachments/297388220231057419/400471386101121024/image.jpg",
				"text": "Achievement Help"
			}
	},
	"search": {
			"title": "All commands matching your search",
			"author": {
				"name": "Cape Info",
				"icon_url": "https://i.imgur.com/6c6q2iC.png"
			},
			"description": "{{output}}",
			"footer": {
				"icon_url": "https://cdn.discordapp.com/attachments/297388220231057419/400471386101121024/image.jpg",
				"text": "Achievement Help"
			}
	},
	"combat - elite dungeons - aminishi? completed it, mate.": {
            "title": "Aminishi? Completed it, mate.",
            "author": {
                "name": "Cape Info",
                "icon_url": "https://i.imgur.com/6c6q2iC.png"
            },
            "description": "[Aminishi? Completed it, mate.](https://runescape.wikia.com/wiki/Aminishi%3F_Completed_it,_mate.) is an achievement that requires the player to defeat all 13 minibosses inside the [Temple of Aminishi](https://runescape.wikia.com/wiki/Temple_of_Aminishi). This is one of the few achievements which can be completed in Story Mode as well as Normal Mode.:\n\nNot every miniboss will not spawn on every run. They can be identified with a red skull icon in the minimap.",
            "thumbnail": {
                "url": "https://i.imgur.com/Shmagnp.png"
            },
            "fields": [
                {
            "name": "Olivia the Chronicler",
            "value": "• [Olivia the Chronicler](https://runescape.wikia.com/wiki/Olivia_the_Chronicler) is in the first room. She can be found near an altar and bell north of the kitchen."
                },
                {
            "name": "Goku the Unrelenting",
            "value": "• [Goku the Unrelenting](https://runescape.wikia.com/wiki/Goku_the_Unrelenting) is in the fourth room. He can be found south of the training room."
                },
                {
            "name": "Sarkhan the Serpentspeaker",
            "value": "• [Sarkhan the Serpentspeaker](https://runescape.wikia.com/wiki/Sarkhan_the_Serpentspeaker) is in the first room. He can be found in the church area, where he is preaching to several [Elite Sotapannas](https://runescape.wikia.com/wiki/Elite_Sotapanna)."
                },
                {
            "name": "Ahoeitu the Chef",
            "value": "• [Ahoeitu the Chef](https://runescape.wikia.com/wiki/Ahoeitu_the_Chef) is in the first room. He can be found in the kitchen in the south-east corner of the room."
                },
                {
            "name": "Xiang the Water-shaper",
            "value": "• [Xiang the Water-shaper](https://runescape.wikia.com/wiki/Xiang_the_Water-shaper) is in the first room. He is found in near the pool in front of the foremost chapel door."
                },
                {
            "name": "Jade the Unruly",
            "value": "• [Jade the Unruly](https://runescape.wikia.com/wiki/Jade_the_Unruly) is in the third room. She is found in the first half of the room in a side path."
                },
                {
            "name": "Ol' Sawtooth",
            "value": "• [Ol' Sawtooth](https://runescape.wikia.com/wiki/Ol%27_Sawtooth) is in the third room. He is found on the right/south side of the large circle room with all the [sea crocodiles](https://runescape.wikia.com/wiki/Sea_crocodile) and [waterfiends](https://runescape.wikia.com/wiki/Waterfiend) in it."
                },
                {
            "name": "Menaphite Guard Captain",
            "value": "• [Menaphite Guard Captain](https://runescape.wikia.com/wiki/Menaphite_guard_captain) is in the third room. He is located on top of the stairs in the northern room full of sea crocodiles that takes place immediately after the large circle room."
                },
                {
            "name": "The Horrific Crassian",
            "value": "• [The Horrific Crassian](https://runescape.wikia.com/wiki/Horrific_crassian) is in the third room. It is where four [Cloaked zealots](https://runescape.wikia.com/wiki/Cloaked_zealot) are found in a supposed ritual area, the same room where the glitched page failed to appear upon the Dungeons release."
                },
                {
            "name": "The Violet Lotus",
            "value": "• [The Violet Lotus](https://runescape.wikia.com/wiki/The_Violet_Lotus) is in the fourth room. He can be found north of the training room."
                },
                {
            "name": "Yukimura of Hanto",
            "value": "• [Yukimura of Hanto](https://runescape.wikia.com/wiki/Yukimura_of_Hanto) is in the fourth room. He is just north of The Violet Lotus."
                },
                {
            "name": "Arhat Paragon",
            "value": "• [Arhat Paragon](https://runescape.wikia.com/wiki/Arhat_paragon) is in the second room. It is found at the very start and center of the chasm where the path is leading to a group of [Arhats](https://runescape.wikia.com/wiki/Arhat_(Temple_of_Aminishi) and [Anagamis](https://runescape.wikia.com/wiki/Anagami_(Temple_of_Aminishi)."
                },
                {
            "name": "Oyu the Quietest",
            "value": "• [Oyu the Quietest](https://runescape.wikia.com/wiki/Oyu_the_Quietest) in the first room. He is found near the globe towards the end of the room."
                },
                {
            "name": "Requirements:",
            "value": "• Impressing the Locals Quest completion | [Runescape Wiki](https://runescape.wikia.com/wiki/Impressing_the_Locals)"
                }
            ],
            "footer": {
                "icon_url": "https://vignette.wikia.nocookie.net/runescape2/images/e/e9/Runescore.png",
                "text": "Runescore awarded: 20"
            }
        },
				"combat - elite dungeons - arc reactor": {},
				"combat - elite dungeons - bless you, seiryu": {},
				"combat - elite dungeons - crassian en masse": {},
				"combat - elite dungeons - died by the blade!": {},
				"combat - elite dungeons - force of a great typhoon": {},
				"combat - elite dungeons - here is my handle": {},
				"combat - elite dungeons - i'll pulverise you!": {},
				"combat - elite dungeons - malignant enigmas": {},
				"combat - elite dungeons - oops! wrong cult!": {},
				"combat - elite dungeons - outflanked 'em in the sanctum": {},
				"combat - elite dungeons - strength of a raging fire": {},
				"combat - elite dungeons - swift as the coursing river": {},
				"combat - elite dungeons - the book of elei": {},
        "combat - elite dungeons - the many hands that write": {
            "title": "The Many Hands That Write",
            "author": {
                "name": "Cape Info",
                "icon_url": "https://i.imgur.com/6c6q2iC.png"
            },
            "description": "[The Many Hands That Write](https://runescape.wikia.com/wiki/The_Many_Hands_That_Write) is an achievement that requires the player to obtain the books [Crassian Allegiance](https://runescape.wikia.com/wiki/Crassian_Allegiance) and [Himiko's Vision](https://runescape.wikia.com/wiki/Himiko%27s_Vision) from bosses in the [Temple of Aminishi](https://runescape.wikia.com/wiki/Temple_of_Aminishi) in either normal or story mode.\n\nCrassian Allegiance is a book found by defeating [The Sanctum Guardian](https://runescape.wikia.com/wiki/The_Sanctum_Guardian) and Himiko's Vision is a book found by defeating [Masuta the Ascended](https://runescape.wikia.com/wiki/Masuta_the_Ascended). Both can be obtained in either normal or story mode, however the drop rate is higher in story mode.",
            "thumbnail": {
                "url": "https://i.imgur.com/Shmagnp.png"
            },
            "fields": [
                {
            "name": "Requirements:",
            "value": "• Impressing the Locals Quest completion | [Runescape Wiki](https://runescape.wikia.com/wiki/Impressing_the_Locals)"
                }
            ],
            "footer": {
                "icon_url": "https://vignette.wikia.nocookie.net/runescape2/images/e/e9/Runescore.png",
                "text": "Runescore awarded: 20"
            }
        },
				"combat - elite dungeons - the purple dart": {},
				"combat - elite dungeons - what does monster examine say about his combat level?": {},
				"combat - general - bone i fired": {},
				"combat - general - order of slayers": {},
				"combat - general - shattering worlds": {},
				"combat - group pvm - best offence": {},
				"combat - group pvm - brothers in arms": {},
				"combat - group pvm - classic rock": {},
				"combat - group pvm - hungry hungry reavers": {},
				"combat - group pvm - matricide": {},
				"combat - group pvm - never eat silk worms": {},
				"combat - group pvm - next to no power": {},
				"combat - group pvm - who's your daddy": {},
				"combat - raids - all together now": {},
				"combat - raids - animal cruelty": {},
				"combat - raids - better not touch": {},
				"combat - raids - cormes and goes": {},
				"combat - raids - day at the aquarium": {},
				"combat - raids - day at the pound": {},
				"combat - raids - going maintenance expert": {},
				"combat - raids - hero of the goebies": {},
				"combat - raids - make friends and influence people": {},
				"combat - raids - prison break": {},
				"combat - raids - rewind": {},
				"combat - solo pvm - all aboard": {},
				"combat - solo pvm - baroo quality": {},
				"combat - solo pvm - bring it all back": {},
				"combat - solo pvm - brothers in arms": {},
				"combat - solo pvm - burn, fury, burn": {},
				"combat - solo pvm - change of the guard": {},
				"combat - solo pvm - classic dragon killing": {},
				"combat - solo pvm - coursing through you": {},
				"combat - solo pvm - dagannoth traffic wardens": {},
				"combat - solo pvm - double swoop": {},
				"combat - solo pvm - fist contact": {},
				"combat - solo pvm - floor is larval": {},
				"combat - solo pvm - glutton for punishment": {},
				"combat - solo pvm - good enough for a goblin": {},
				"combat - solo pvm - graardone": {},
				"combat - solo pvm - hail to the queen": {},
				"combat - solo pvm - i got this": {},
				"combat - solo pvm - in the spirit of things": {},
				"combat - solo pvm - k'ril will be done": {},
				"combat - solo pvm - k'rilow": {},
				"combat - solo pvm - like a boss": {},
				"combat - solo pvm - loyal subject": {},
				"combat - solo pvm - lumbridge strikes back": {},
				"combat - solo pvm - naturist": {},
				"combat - solo pvm - safety dance": {},
				"combat - solo pvm - stand your ground": {},
				"combat - solo pvm - stuffed with anima": {},
				"combat - solo pvm - sunshine through the rain": {},
				"combat - solo pvm - telos if you're angry": {},
				"combat - solo pvm - they all fell down": {},
				"combat - solo pvm - through the fire and flames": {},
				"combat - solo pvm - traitorous": {},
				"combat - solo pvm - unionised": {},
				"combat - solo pvm - wolf pack": {},
				"exploration - menaphos - 'phite club": {},
				"exploration - menaphos - 'phite for your right": {},
				"exploration - menaphos - all abuzz": {},
				"exploration - menaphos - boys to menaphites": {},
				"exploration - menaphos - class crown": {},
				"exploration - menaphos - crocadile tears": {},
				"exploration - menaphos - feline good": {},
				"exploration - menaphos - game of tombs": {},
				"exploration - menaphos - lock, stock, and barrel": {},
				"exploration - menaphos - our man in the north": {},
				"exploration - menaphos - rock and roll": {},
				"exploration - menaphos - seagullible": {},
				"exploration - menaphos - slay bells ring": {},
				"exploration - menaphos - squishing level": {},
				"exploration - menaphos - the jack of spades": {},
				"exploration - menaphos - to the bone": {},
				"exploration - new varrock - bank-z": {},
				"exploration - new varrock - cat's bane": {},
				"exploration - new varrock - coin of the realm": {},
				"exploration - new varrock - dark imperator-ment": {},
				"exploration - new varrock - guard is dead": {},
				"exploration - new varrock - hand exchange": {},
				"exploration - new varrock - hide and seek": {},
				"exploration - new varrock - micro brew": {},
				"exploration - new varrock - moo-er of all bombs": {},
				"exploration - new varrock - mummy returns": {},
				"exploration - new varrock - pick all": {},
				"exploration - new varrock - pick half": {},
				"exploration - new varrock - pick one": {},
				"exploration - new varrock - ready, deady, cook": {},
				"exploration - new varrock - scrying game": {},
				"exploration - new varrock - set tasks easy": {},
				"exploration - new varrock - set tasks elite": {},
				"exploration - new varrock - set tasks hard": {},
				"exploration - new varrock - set tasks medium": {},
				"exploration - new varrock - south and west side story": {},
				"exploration - new varrock - they had a gudrun": {},
				"exploration - new varrock - tier gear": {},
				"exploration - new varrock - top pick": {},
				"exploration - new varrock - trade parade": {},
				"exploration - wushanko: the arc - arc i - flag fall": {},
				"exploration - wushanko: the arc - arc ii - head of the family": {},
				"exploration - wushanko: the arc - arc iii - spiritual enlightenment": {},
				"exploration - wushanko: the arc - arc iv - jed hunter": {},
				"exploration - wushanko: the arc - arc ix - damage control": {},
				"exploration - wushanko: the arc - arc v - eye for an eye": {},
				"exploration - wushanko: the arc - arc vi - harbinger of doom": {},
				"exploration - wushanko: the arc - arc vii - tuai leit's own": {},
				"exploration - wushanko: the arc - arc viii - ghosts from the past": {},
				"exploration - wushanko: the arc - arc x - final destination": {},
				"exploration - wushanko: the arc - berries of the arc": {},
				"exploration - wushanko: the arc - birds of the arc": {},
				"exploration - wushanko: the arc - castaways of the arc": {},
				"exploration - wushanko: the arc - flippers": {},
				"exploration - wushanko: the arc - kami spirits of the arc": {},
				"exploration - wushanko: the arc - mushrooms of the arc": {},
				"exploration - wushanko: the arc - rewards": {},
				"exploration - wushanko: the arc - salty": {},
				"exploration - wushanko: the arc - unlocking more waiko": {},
				"exploration - wushanko: the arc - upgrading all of the waiko": {},
				"exploration - wushanko: the arc - wushanko isles: the arc": {},
				"minigames - general - a-voiding conflict": {},
				"minigames - general - altar explorer": {},
				"minigames - general - beggars can't be choosers": {},
				"minigames - general - careful, there are snakes": {},
				"minigames - general - claymation": {},
				"minigames - general - disowned": {},
				"minigames - general - going down with the ship": {},
				"minigames - general - it's not called surging tombs": {},
				"minigames - general - little leaguer": {},
				"minigames - general - magister smagister": {},
				"minigames - general - seeing lava": {},
				"minigames - general - source of denial": {},
				"minigames - general - tokhaar-mok": {},
				"minigames - general - unlucky for some": {},
				"minigames - general - varrock calls for aid!": {},
				"minigames - general - what year is it?": {},
				"minigames - general - who do broodoo?": {},
				"minigames - general - you're it": {},
				"minigames - treasure trails - balance combat triangle": {},
				"minigames - treasure trails - clued-up": {},
				"minigames - treasure trails - digging for treasure": {},
				"minigames - treasure trails - diving for clues": {},
				"minigames - treasure trails - fill them all!": {},
				"minigames - treasure trails - globetrotter": {},
				"minigames - treasure trails - skeletrail horror": {},
				"minigames - treasure trails - slide to the left": {},
				"minigames - treasure trails - towering over us all": {},
				"minigames - treasure trails - treasure seeker": {},
				"minigames - treasure trails - untangled": {},
				"minigames - treasure trails - what's in the hole?": {},
				"miscellaneous - clan - a wizard did it": {},
				"miscellaneous - clan - castles in the sky": {},
				"miscellaneous - clan - citadelementary": {},
				"miscellaneous - clan - faceless and ready": {},
				"miscellaneous - general - going for a punt": {},
				"miscellaneous - general - great gielinor run": {},
				"miscellaneous - general - open bar": {},
				"miscellaneous - general - second shrubbery": {},
				"miscellaneous - general - seven colours in their hat": {},
				"miscellaneous - miniquest - a brief history of telescopes": {},
				"miscellaneous - miniquest - a guild of our own": {},
				"miscellaneous - miniquest - abyssal reach": {},
				"miscellaneous - miniquest - ali the trader": {},
				"miscellaneous - miniquest - arc i - flag fall": {},
				"miscellaneous - miniquest - arc ii - head of the family": {},
				"miscellaneous - miniquest - arc iii - spiritual enlightenment": {},
				"miscellaneous - miniquest - arc iv - jed hunter": {},
				"miscellaneous - miniquest - arc ix - damage control": {},
				"miscellaneous - miniquest - arc v - an eye for an eye": {},
				"miscellaneous - miniquest - arc vi - harbinger of doom": {},
				"miscellaneous - miniquest - arc vii - tuai leit's own": {},
				"miscellaneous - miniquest - arc viii - ghosts from the past": {},
				"miscellaneous - miniquest - arc x - final destination": {},
				"miscellaneous - miniquest - around the world in six ways": {},
				"miscellaneous - miniquest - banking history": {},
				"miscellaneous - miniquest - benedict's world tour, part 1": {},
				"miscellaneous - miniquest - benedict's world tour, part 2": {},
				"miscellaneous - miniquest - deadlier catch": {},
				"miscellaneous - miniquest - desert-ed ghosts": {},
				"miscellaneous - miniquest - from tiny acorns": {},
				"miscellaneous - miniquest - ivan is flailing": {},
				"miscellaneous - miniquest - kharshai's memories": {},
				"miscellaneous - miniquest - koschei's cache": {},
				"miscellaneous - miniquest - kudos to you": {},
				"miscellaneous - miniquest - lost her marbles": {},
				"miscellaneous - miniquest - lost toys": {},
				"miscellaneous - miniquest - master otto": {},
				"miscellaneous - miniquest - milk of chocolate, snape of grass": {},
				"miscellaneous - miniquest - myreque in memoriam": {},
				"miscellaneous - miniquest - nomad's genesis": {},
				"miscellaneous - miniquest - one foot in the grave": {},
				"miscellaneous - miniquest - pious prayers": {},
				"miscellaneous - miniquest - scabigail": {},
				"miscellaneous - miniquest - sheep shearer": {},
				"miscellaneous - miniquest - skeletal wishes": {},
				"miscellaneous - miniquest - soft kitty, purple kitty": {},
				"miscellaneous - miniquest - stay safe": {},
				"miscellaneous - miniquest - stay secure": {},
				"miscellaneous - miniquest - tell tale tarn": {},
				"miscellaneous - miniquest - the general's shadow": {},
				"miscellaneous - miniquest - the hunt for surok": {},
				"miscellaneous - miniquest - to ga'al or not to ga'al": {},
				"miscellaneous - miniquest - what's mine is also doric's": {},
				"miscellaneous - miniquest - witch's potion": {},
				"miscellaneous - miniquest - you be dead": {},
				"miscellaneous - miniquest -slime and snails and god wars tales": {},
				"skills - divination - business is booning!": {},
				"skills - divination - collecting memorabilia": {},
				"skills - divination - enrichment programme": {},
				"skills - divination - just give me a sign": {},
				"skills - divination - let's enhance": {},
				"skills - divination - mighty morphing": {},
				"skills - divination - simply divine": {},
				"skills - divination - the archivist": {},
				"skills - divination - what an experience": {},
				"skills - divination portentially hazardous": {},
				"skills - diviniation - divine retribution": {},
				"skills - diviniation - energy generator": {},
				"skills - fishing - boosted animal": {},
				"skills - fishing - fancy turtle-back": {},
				"skills - fishing - frenzied": {},
				"skills - fishing - make a wish": {},
				"skills - fishing - my precious!": {},
				"skills - fishing - ruler of the sea": {},
				"skills - fishing - up for sail": {},
				"skills - thieving - pilferin' in asgarnia": {},
				"skills - thieving - pilferin' in kandarin": {},
				"skills - thieving - pilferin' in kharadian desert": {},
				"skills - thieving - pilferin' in misthalin": {},
				"skills - thieving - pilferin' the hidden ones": {},
				"skills - thieving - the world is a safe place": {}
}